<section>
    
    <header>
        <h2>Nastavení webu</h2>
    </header>
    <form action="" method="post">
<table class="default">
    <tr><td>Klíčová slova :</td><td><input type="text" name="keywords" size="35" value="<?= $keywords ?>" ></td></tr>
    <tr><td>Popis webu :</td><td><input type="text" name="description" size="35" value="<?= $description ?>" ></td></tr>
    <tr><td>Titulek webu :</td><td><input type="text" name="title" size="15" value="<?= $title ?>" ></td></tr>
    <tr><td>Footer :</td><td><textarea id="e1m1" name="footer" rows="15"> <?= $footer ?></textarea></td></tr>
    <tr><td colspan="2" align="right"><input style="text-align: right;" type="submit" name="Ulozit" value="Uložit"</td></tr>
</table>
    </form>
</section>