<section >
				<header>
						<h2>Kontaktní formulář</h2>
						<p>Kontaktujte nás odesláním formuláře níže.</p>
				</header>
				<div class="content style4 featured">
					<div class="container 75%">
						<form method="post" action="#">
							<div class="row 50%">
								<div class="6u 12u(mobile)"><input type="text" name="jmeno" placeholder="Jméno" /></div>
								<div class="6u 12u(mobile)"><input type="text" name="email" placeholder="Email" /></div>
							</div>
							<div class="row 50%">
								<div class="12u"><textarea name="message" name="zprava" placeholder="Zpráva"></textarea></div>
							</div>
							<div class="row">
								<div class="12u">
									<ul class="actions">
										<li><input type="submit" class="buttonf" value="Odeslat zprávu" /></li>
										<li><input type="reset" class="buttonf alt" value="Vymazat formulář" /></li>
									</ul>
								</div>
							</div>
						</form>
					</div>
				</div>
</section>
