<section >
				<header>
						<h2>Přihlášení do administrace PMAutocisteni.cz</h2>
						<p>Vyplňte jméno a heslo.</p>
                                                <p><?= $chyba ?></p>
				</header>
				<div class="content style4 featured">
					<div class="container 25%">
						<form method="post" name="admin" action="">
							<div class="row 80%">
								<div class="12u 12u(mobile)"><input type="text" name="login" placeholder="Login" /></div>
							</div>
							<div class="row 80%">
								<div class="12u 12u(mobile)"><input type="password" name="heslo"  /></div>
							</div>
							<div class="row">
								<div class="12u">
									<ul class="actions">
										<li><input type="submit" name="prihlaseni" class="buttonf" value="Přihlásit" /></li>
									</ul>
								</div>
							</div>
						</form>
					</div>
				</div>
</section>
